feat(multi-support): release matrix for staging and prod

diff --git a/.github/workflows/release-deploy.yml b/.github/workflows/release-deploy.yml
--- a/.github/workflows/release-deploy.yml
+++ b/.github/workflows/release-deploy.yml
@@ -24,15 +24,22 @@ on:
         required: false
         type: string
       ecr_repository:
-        required: true
+        required: false
+        type: string
+      ecr_repositories:
+        required: false
         type: string
       terraform_version:
         description: 'Terraform version'
         type: string
         default: '1.9.8'
       service_name:
-        required: true
+        required: false
         type: string
+      services:
+        required: false
+        type: string
+        description: 'Services names when deploying multiple services. Should be a list of objects with keys "directory" and "name" e.g. [{"directory": "core", "name": "apro-core-service"}]'
       cluster_name_staging:
         required: true
         type: string
@@ -64,26 +71,51 @@ jobs:
           ECR_REPOSITORY: ${{ inputs.ecr_repository }}
           VERSION_TAG: ${{ github.event.release.tag_name }}
 
+  unify-services:
+    name: '🤝 Unify service inputs'
+    runs-on: ubuntu-latest
+    outputs:
+      final_services: ${{ steps.unify-services.outputs.final_services }}
+    steps:
+      - name: 🤝 Unify service inputs
+        id: unify-services
+        run: |
+          if [ -n "${{ inputs.service_name }}" ] && [ -z "${{ inputs.services }}" ]; then
+            echo 'final_services=[{"directory":".","name":"${{ inputs.service_name }}"}]' >> $GITHUB_OUTPUT
+
+          elif [ -z "${{ inputs.service_name }}" ] && [ -n "${{ inputs.services }}" ]; then
+            echo 'final_services=${{ inputs.services }}' >> $GITHUB_OUTPUT
+
+          else
+            echo "ERROR: Exactly one of 'service_name' or 'services' must be set." >&2
+            exit 1
+          fi
+
   deploy-to-staging:
     name: '🚀 Deploy to staging'
+    strategy:
+      matrix:
+        include: ${{ fromJSON(needs.unify-services.outputs.final_services) }}
     environment: staging
     if: ${{ inputs.deploy_to_staging == true }}
     needs:
       - version-tag
+      - unify-services
     runs-on: ubuntu-latest
     steps:
       - name: 📁 Checkout
         uses: actions/checkout@v4
 
       - name: 🚀 Deploy to staging
-        uses: aproorg/github-workflows/.github/actions/deploy-ecs-service@main
+        uses: aproorg/github-workflows/.github/actions/deploy-ecs-service@support-custom-build-scripts
         with:
           AWS_REGION: ${{ inputs.aws_region }}
           AWS_DEPLOYMENT_ROLE: ${{ inputs.github_ci_role_staging_arn }}
           ENVIRONMENT: staging
           IMAGE_TAG: ${{ github.event.release.tag_name }}
           TERRAFORM_VERSION: ${{ inputs.terraform_version }}
-          SERVICE_NAME: ${{ inputs.service_name}}
+          TERRAFORM_PATH: '${{ matrix.directory }}/terraform'
+          SERVICE_NAME: ${{ matrix.name }}
           CLUSTER_NAME: ${{ inputs.cluster_name_staging }}
           PRE_APPLIED_RESOURCES: ${{ inputs.pre_applied_resources }}
 
@@ -91,6 +123,9 @@ jobs:
     name: '🚀 Deploy to prod'
     environment: prod
     if: ${{ inputs.deploy_to_prod == true }}
+    strategy:
+      matrix:
+        include: ${{ fromJSON(needs.unify-services.outputs.final_services) }}
     needs:
       - version-tag
     runs-on: ubuntu-latest
@@ -99,13 +134,14 @@ jobs:
         uses: actions/checkout@v4
 
       - name: 🚀 Deploy to prod
-        uses: aproorg/github-workflows/.github/actions/deploy-ecs-service@main
+        uses: aproorg/github-workflows/.github/actions/deploy-ecs-service@support-custom-build-scripts
         with:
           AWS_REGION: ${{inputs.aws_region}}
           AWS_DEPLOYMENT_ROLE: ${{ inputs.github_ci_role_prod_arn }}
           ENVIRONMENT: prod
           IMAGE_TAG: ${{ github.event.release.tag_name }}
           TERRAFORM_VERSION: ${{ inputs.terraform_version }}
-          SERVICE_NAME: ${{ inputs.service_name}}
-          CLUSTER_NAME: ${{ inputs.cluster_name_prod }}
+          TERRAFORM_PATH: '${{ matrix.directory }}/terraform'
+          SERVICE_NAME: ${{ matrix.name }}
+          CLUSTER_NAME: ${{ inputs.cluster_name_staging }}
           PRE_APPLIED_RESOURCES: ${{ inputs.pre_applied_resources }}
